// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: remote.proto

package remoter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpuStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Core          int32                  `protobuf:"varint,1,opt,name=core,proto3" json:"core,omitempty"`
	Load          float32                `protobuf:"fixed32,2,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuStat) Reset() {
	*x = CpuStat{}
	mi := &file_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuStat) ProtoMessage() {}

func (x *CpuStat) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuStat.ProtoReflect.Descriptor instead.
func (*CpuStat) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{0}
}

func (x *CpuStat) GetCore() int32 {
	if x != nil {
		return x.Core
	}
	return 0
}

func (x *CpuStat) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

type RamStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedPercent   float32                `protobuf:"fixed32,1,opt,name=usedPercent,proto3" json:"usedPercent,omitempty"`
	UsedGb        float32                `protobuf:"fixed32,2,opt,name=usedGb,proto3" json:"usedGb,omitempty"`
	TotalGb       float32                `protobuf:"fixed32,3,opt,name=totalGb,proto3" json:"totalGb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RamStat) Reset() {
	*x = RamStat{}
	mi := &file_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RamStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RamStat) ProtoMessage() {}

func (x *RamStat) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RamStat.ProtoReflect.Descriptor instead.
func (*RamStat) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{1}
}

func (x *RamStat) GetUsedPercent() float32 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *RamStat) GetUsedGb() float32 {
	if x != nil {
		return x.UsedGb
	}
	return 0
}

func (x *RamStat) GetTotalGb() float32 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

type DiskStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mountPoint,proto3" json:"mountPoint,omitempty"`
	UsedPercent   float32                `protobuf:"fixed32,3,opt,name=usedPercent,proto3" json:"usedPercent,omitempty"`
	UsedGb        float32                `protobuf:"fixed32,4,opt,name=usedGb,proto3" json:"usedGb,omitempty"`
	TotalGb       float32                `protobuf:"fixed32,5,opt,name=totalGb,proto3" json:"totalGb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStat) Reset() {
	*x = DiskStat{}
	mi := &file_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStat) ProtoMessage() {}

func (x *DiskStat) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStat.ProtoReflect.Descriptor instead.
func (*DiskStat) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{2}
}

func (x *DiskStat) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStat) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskStat) GetUsedPercent() float32 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *DiskStat) GetUsedGb() float32 {
	if x != nil {
		return x.UsedGb
	}
	return 0
}

func (x *DiskStat) GetTotalGb() float32 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

type IpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=Ips,proto3" json:"Ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpInfo) Reset() {
	*x = IpInfo{}
	mi := &file_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpInfo) ProtoMessage() {}

func (x *IpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpInfo.ProtoReflect.Descriptor instead.
func (*IpInfo) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{3}
}

func (x *IpInfo) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type InfoRequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Cpu           []*CpuStat             `protobuf:"bytes,2,rep,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           *RamStat               `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Disk          []*DiskStat            `protobuf:"bytes,4,rep,name=disk,proto3" json:"disk,omitempty"`
	Ips           *IpInfo                `protobuf:"bytes,5,opt,name=ips,proto3" json:"ips,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequestMsg) Reset() {
	*x = InfoRequestMsg{}
	mi := &file_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequestMsg) ProtoMessage() {}

func (x *InfoRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequestMsg.ProtoReflect.Descriptor instead.
func (*InfoRequestMsg) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{4}
}

func (x *InfoRequestMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InfoRequestMsg) GetCpu() []*CpuStat {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *InfoRequestMsg) GetRam() *RamStat {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *InfoRequestMsg) GetDisk() []*DiskStat {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *InfoRequestMsg) GetIps() *IpInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *InfoRequestMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_remote_proto protoreflect.FileDescriptor

const file_remote_proto_rawDesc = "" +
	"\n" +
	"\fremote.proto\x12\aremoter\"1\n" +
	"\aCpuStat\x12\x12\n" +
	"\x04core\x18\x01 \x01(\x05R\x04core\x12\x12\n" +
	"\x04load\x18\x02 \x01(\x02R\x04load\"]\n" +
	"\aRamStat\x12 \n" +
	"\vusedPercent\x18\x01 \x01(\x02R\vusedPercent\x12\x16\n" +
	"\x06usedGb\x18\x02 \x01(\x02R\x06usedGb\x12\x18\n" +
	"\atotalGb\x18\x03 \x01(\x02R\atotalGb\"\x96\x01\n" +
	"\bDiskStat\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"mountPoint\x18\x02 \x01(\tR\n" +
	"mountPoint\x12 \n" +
	"\vusedPercent\x18\x03 \x01(\x02R\vusedPercent\x12\x16\n" +
	"\x06usedGb\x18\x04 \x01(\x02R\x06usedGb\x12\x18\n" +
	"\atotalGb\x18\x05 \x01(\x02R\atotalGb\"\x1a\n" +
	"\x06IpInfo\x12\x10\n" +
	"\x03Ips\x18\x01 \x03(\tR\x03Ips\"\xdc\x01\n" +
	"\x0eInfoRequestMsg\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\x03cpu\x18\x02 \x03(\v2\x10.remoter.CpuStatR\x03cpu\x12\"\n" +
	"\x03ram\x18\x03 \x01(\v2\x10.remoter.RamStatR\x03ram\x12%\n" +
	"\x04disk\x18\x04 \x03(\v2\x11.remoter.DiskStatR\x04disk\x12!\n" +
	"\x03ips\x18\x05 \x01(\v2\x0f.remoter.IpInfoR\x03ips\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestampB\vZ\t./remoterb\x06proto3"

var (
	file_remote_proto_rawDescOnce sync.Once
	file_remote_proto_rawDescData []byte
)

func file_remote_proto_rawDescGZIP() []byte {
	file_remote_proto_rawDescOnce.Do(func() {
		file_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)))
	})
	return file_remote_proto_rawDescData
}

var file_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_remote_proto_goTypes = []any{
	(*CpuStat)(nil),        // 0: remoter.CpuStat
	(*RamStat)(nil),        // 1: remoter.RamStat
	(*DiskStat)(nil),       // 2: remoter.DiskStat
	(*IpInfo)(nil),         // 3: remoter.IpInfo
	(*InfoRequestMsg)(nil), // 4: remoter.InfoRequestMsg
}
var file_remote_proto_depIdxs = []int32{
	0, // 0: remoter.InfoRequestMsg.cpu:type_name -> remoter.CpuStat
	1, // 1: remoter.InfoRequestMsg.ram:type_name -> remoter.RamStat
	2, // 2: remoter.InfoRequestMsg.disk:type_name -> remoter.DiskStat
	3, // 3: remoter.InfoRequestMsg.ips:type_name -> remoter.IpInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remote_proto_init() }
func file_remote_proto_init() {
	if File_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_proto_goTypes,
		DependencyIndexes: file_remote_proto_depIdxs,
		MessageInfos:      file_remote_proto_msgTypes,
	}.Build()
	File_remote_proto = out.File
	file_remote_proto_goTypes = nil
	file_remote_proto_depIdxs = nil
}
