// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: service.proto

package remoter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RemoterClient is the client API for Remoter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoterClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Remoter_ConnectClient, error)
}

type remoterClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoterClient(cc grpc.ClientConnInterface) RemoterClient {
	return &remoterClient{cc}
}

func (c *remoterClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Remoter_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Remoter_ServiceDesc.Streams[0], "/remoter.Remoter/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoterConnectClient{stream}
	return x, nil
}

type Remoter_ConnectClient interface {
	Send(*InfoRequestMsg) error
	Recv() (*NilResponseMsg, error)
	grpc.ClientStream
}

type remoterConnectClient struct {
	grpc.ClientStream
}

func (x *remoterConnectClient) Send(m *InfoRequestMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoterConnectClient) Recv() (*NilResponseMsg, error) {
	m := new(NilResponseMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoterServer is the server API for Remoter service.
// All implementations must embed UnimplementedRemoterServer
// for forward compatibility
type RemoterServer interface {
	Connect(Remoter_ConnectServer) error
	mustEmbedUnimplementedRemoterServer()
}

// UnimplementedRemoterServer must be embedded to have forward compatible implementations.
type UnimplementedRemoterServer struct {
}

func (UnimplementedRemoterServer) Connect(Remoter_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRemoterServer) mustEmbedUnimplementedRemoterServer() {}

// UnsafeRemoterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoterServer will
// result in compilation errors.
type UnsafeRemoterServer interface {
	mustEmbedUnimplementedRemoterServer()
}

func RegisterRemoterServer(s grpc.ServiceRegistrar, srv RemoterServer) {
	s.RegisterService(&Remoter_ServiceDesc, srv)
}

func _Remoter_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoterServer).Connect(&remoterConnectServer{stream})
}

type Remoter_ConnectServer interface {
	Send(*NilResponseMsg) error
	Recv() (*InfoRequestMsg, error)
	grpc.ServerStream
}

type remoterConnectServer struct {
	grpc.ServerStream
}

func (x *remoterConnectServer) Send(m *NilResponseMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoterConnectServer) Recv() (*InfoRequestMsg, error) {
	m := new(InfoRequestMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Remoter_ServiceDesc is the grpc.ServiceDesc for Remoter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Remoter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remoter.Remoter",
	HandlerType: (*RemoterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Remoter_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
